export type BookingFormInputs = {
    awbNumber: string,
    referenceNumber: string,
    bookedDate: string,
    courier: number,
    shipperName: string,
    origin: string,
    doxType: number,
    receiverName: string,
    destination: string,
    shipmentMode: number,
    transportMode: number,
    coCourier: number,
    bookingAmount?: number,
    billAmount?: number,
    actualWeight?: number,
    bookedBy: string,
    paymentMode: string,
    remarks: string,
    internalRemarks: string,
    deliveryOfficeLocation: string,
    additionalContacts: string,
    additionalWeights: string,
    additionalLeaf: string,
    thirdPartyNumber: string,
};
