export interface Booking {
    id?: number;
    awbNumber: string;
    referenceNumber: string;
    bookedDate: Date;
    shipperName?: string;
    origin?: string;
    receiverName?: string;
    destination: string;
    courier: number;
    doxType: number;
    shipmentMode: number;
    transportMode: number;
    shipmentStatus: number;
    deliveredDate?: Date;
    receivedPersonName?: string;
    receivedPersonRelation?: string;
    remarks?: string;
    deliveryOfficeAddress?: string;
    additionalContacts?: string;
    additionalWeights?: string;
    additionalLeaf?: string;
    bookingAmount?: number;
    billAmount?: number;
    createdDateTime?: Date;
    createdBy?: string;
    updatedTimestamp?: Date;
    updatedBy?: string;
}
